# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c18bd5512628d899c87d5e09333eec4074b165d20c2a20528bfef256837618dc8c20a1e09a6732061c061b92588aaa5fb64045a6a7551da5aa2c03264a217939

test:
  secret_key_base: 8a2419ae0eebcad70b90139391232203f9725333edbfbeaf687a0b4f301f98a0b04409fc39251dc7f6deb90db31ab677f766f7a5f5ea269f51c302d8ee22e6bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
